logging.pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: externalcreds

  config.import: optional:classpath:rendered/providers.yaml

  datasource:
    hikari.connection-timeout: 5000
    password: ${DATABASE_USER_PASSWORD:ecmpwd}
    url: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:5432/ecm
    username: ${DATABASE_USER:ecmuser}

  main.banner-mode: off

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
