externalcreds.sam-address: ${SAM_ADDRESS:https://sam.dsde-dev.broadinstitute.org}

logging:
  level.bio.terra.externalcreds: ${EXTERNALCREDS_LOG_LEVEL:debug}
  pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: externalcreds

  config.import: optional:classpath:rendered/providers.yaml;classpath:rendered/version.properties

  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 8 # cpu count * 2 https://kwahome.medium.com/database-connections-less-is-more-86c406b6fad
    password: ${DATABASE_USER_PASSWORD:ecmpwd}
    url: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:5432/${DATABASE_NAME:ecm}
    username: ${DATABASE_USER:ecmuser}

  jackson.serialization.indent_output: true

  main.banner-mode: off

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false

# This governs how database transactions are retried. TransientDataAccessExceptions,
# generally cause by concurrency failures, are retried quickly, random 10-20ms delay, and up to
# 100 times total. RecoverableDataAccessException and CannotCreateTransactionExceptions, such as
# database is down, are retried with exponential back off starting at 1s delay up to 4 times total.
terra.common.retry.transaction:
  fast-retry-exceptions:
    - org.springframework.dao.TransientDataAccessException
  fast-retry-max-attempts: 100
  fast-retry-min-back-off-period: 10ms
  fast-retry-max-back-off-period: 20ms
  slow-retry-exceptions:
    - org.springframework.dao.RecoverableDataAccessException
    - org.springframework.transaction.CannotCreateTransactionException
  slow-retry-max-attempts: 4
  slow-retry-initial-interval: 1s
  slow-retry-multiplier: 2
