externalcreds:
  sam-base-path: ${SAM_ADDRESS:https://sam.dsde-dev.broadinstitute.org}
  background-job-interval-mins: 5
  visa-and-passport-refresh-interval: 30m

logging:
  level.bio.terra.externalcreds: ${EXTERNALCREDS_LOG_LEVEL:debug}
  pattern.level: '%X{requestId} %5p'

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080

spring:
  application.name: externalcreds

  config.import: optional:classpath:rendered/providers.yaml;classpath:rendered/version.properties;classpath:rendered/allowed_jwks.yaml

  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 8 # cpu count * 2 https://kwahome.medium.com/database-connections-less-is-more-86c406b6fad
    password: ${DATABASE_USER_PASSWORD:ecmpwd}
    url: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:5432/${DATABASE_NAME:ecm}
    username: ${DATABASE_USER:ecmuser}

  jackson.serialization.indent_output: true

  main.banner-mode: off

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false

terra.common:
  tracing:
    stackdriverExportEnabled: ${CLOUD_TRACE_ENABLED:false}
    samplingRate: ${SAMPLING_PROBABILITY:0}
