externalcreds:
  sam-base-path: ${SAM_ADDRESS:https://sam.dsde-dev.broadinstitute.org}
  background-job-interval-mins: 5
  token-validation-duration: 50m # with 5m job interval, 50m allows 2 attempts to validate before 60m expires
  visa-and-passport-refresh-duration: 30m
  # only enable google pubsub topic in live envs
  authorization-change-events-enabled: ${AUTHORIZATION_CHANGE_EVENTS_ENABLED:false}
  # name from: https://github.com/broadinstitute/terraform-ap-modules/blob/master/externalcreds/pubsub.tf
  authorization-change-event-topic-name: projects/${SERVICE_GOOGLE_PROJECT:broad-dsde-dev}/topics/ecm-events
  # allowed JWT encryption algorithms
  allowed-jwt-algorithms: [ RS256, ES256 ]
  kms-configuration:
    service-google-project: ${SERVICE_GOOGLE_PROJECT:broad-dsde-dev}
    key-ring-id: ${KMS_KEYRING_ID:ecm-dev-kms-symmetric-key-ring}
    key-id: ${KMS_KEY_ID:ecm-dev-kms-symmetric-key-for-ssh-key-encrypt-decrypt}
    key-ring-location: ${kMS_KEY_LOCATION:us-central1}
    ssh-key-pair-refresh-duration: ${KMS_KEY_REFRESH_DURATION:90d}
  providers:
    github:
      clientId: "${GITHUB_CLIENT_ID}"
      clientSecret: "${GITHUB_CLIENT_SECRET}"
      externalIdClaim: "login"
      issuer: "https://github.com"
      linkLifespan: "15d"
      scopes: ""
      userNameAttributeName: "login"
      revokeEndpoint: "https://api.github.com/installation/token"
      userInfoEndpoint: "https://api.github.com/user"
      authorizationEndpoint: "${externalcreds.providers.github.issuer}/login/oauth/authorize"
      tokenEndpoint: "${externalcreds.providers.github.issuer}/login/oauth/access_token"

logging:
  level.bio.terra.externalcreds: ${EXTERNALCREDS_LOG_LEVEL:debug}
  pattern.level: '%X{requestId} %5p'

management:
  # For Micrometer metrics gathering
  endpoints:
    web:
      exposure:
        # Expose all management endpoints in Spring Boot
        include: "*"
  metrics:
    distribution:
      # Used to publish a histogram suitable for computing aggregable (across dimensions) percentile
      # latency approximations in Prometheus (by using histogram_quantile)
      # For more information: https://micrometer.io/docs/concepts#_histograms_and_percentiles
      minimum-expected-value[http.server.requests]: 200ms
      maximum-expected-value[http.server.requests]: 60s
      percentiles-histogram[http.server.requests]: true
  server:
    # Expose metrics on a different port than our app so that they aren't exposed with other endpoints
    port: 9098

otel:
  sdk:
    disabled: false # set to true to disable all open telemetry features

  springboot:
    resource:
      attributes:
        service:
          name: ${spring.application.name}

server:
  compression:
    enabled: true
    mime-types: text/css,application/javascript
  port: 8080
  error:
    whitelabel:
      enabled: false # error management fallback on Tomcat default error page
    # To prevent Tomcat's default error page disclosing information :
    include-binding-errors: never
    include-message: never
    include-stacktrace: never # most important one : prevent Tomcat version disclose
    include-exception: false

spring:
  # application name and version are used to populate the logging serviceContext
  # https://github.com/DataBiosphere/terra-common-lib/blob/480ab3daae282ddff0fef8dc329494a4422e32f1/src/main/java/bio/terra/common/logging/GoogleJsonLayout.java#L118
  application.name: externalcreds
  application.version: ${externalcreds.version.gitHash:unknown}

  config.import: optional:classpath:rendered/version.properties;optional:classpath:rendered/allowed_jwks.yaml;optional:classpath:rendered/allowed_jwt_issuers.yaml

  datasource:
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 8 # cpu count * 2 https://kwahome.medium.com/database-connections-less-is-more-86c406b6fad
    password: ${DATABASE_USER_PASSWORD:ecmpwd}
    url: jdbc:postgresql://${DATABASE_HOSTNAME:localhost}:5432/${DATABASE_NAME:ecm}
    username: ${DATABASE_USER:ecmuser}

  jackson:
    serialization.indent_output: true
    default-property-inclusion: non_null # this prevents a problem serializing VisaCriterion in openapi where `type` is included a second time with null value

  main.banner-mode: off

  profiles.include:
    - ${DEPLOY_ENV:dev}

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          must-revalidate: true
        use-last-modified: false
  task.scheduling.pool.size: 2

terra.common:
  google:
    tracing:
      enabled: ${CLOUD_TRACE_ENABLED:false}
  tracing:
    samplingRatio: ${SAMPLING_PROBABILITY:0}

---
#non-prod environments
spring.config.activate.on-profile: '!prod'
externalcreds:
  providers:
    ras:
      clientId: "${RAS_CLIENT_ID}"
      clientSecret: "${RAS_CLIENT_SECRET}"
      externalIdClaim: "preferred_username"
      scopes: [ "openid","email","ga4gh_passport_v1","profile" ]
      linkLifespan: "15d"
      issuer: "https://stsstg.nih.gov"
      revokeEndpoint: "${externalcreds.providers.ras.issuer}/auth/oauth/v2/token/revoke?token_type_hint=refresh_token&token=%s"
      userInfoEndpoint: "${externalcreds.providers.ras.issuer}/openid/connect/v1.1/userinfo"
      validationEndpoint: "${externalcreds.providers.ras.issuer}/passport/validate"

---
spring.config.activate.on-profile: 'dev'
externalcreds:
  providers:
    ras:
      allowedRedirectUriPatterns: [ "https://bvdp-saturn-dev.appspot.com/ecm-callback" ]
    github:
      allowedRedirectUriPatterns: [ "https://bvdp-saturn-dev.appspot.com/oauth_callback" ]
---
spring.config.activate.on-profile: 'staging'
externalcreds:
  providers:
    ras:
      allowedRedirectUriPatterns: [ "https://bvdp-saturn-staging.appspot.com/ecm-callback" ]
    github:
      allowedRedirectUriPatterns: [ "https://bvdp-saturn-staging.appspot.com/oauth_callback" ]
---
spring.config.activate.on-profile: 'prod'
externalcreds:
  providers:
    ras:
      allowedRedirectUriPatterns: [ "https://app.terra.bio/ecm-callback" ]
    github:
      allowedRedirectUriPatterns: [ "https://app.terra.bio/oauth_callback" ]
