name: 'integration-test'
description: 'Runs an integration test and uploads the results'
author: 'swessel'
inputs:
  test-server:
    description: 'Test runner server specification file'
    required: true
    default: 'ecm-dev.json'
  test:
    description: 'Test suite or config to run'
    required: true
    default: 'suites/dev/FullIntegration.json'
runs:
  using: "composite"
  steps:
    # We run the test as one script, collecting the test result
    - name: Run the test
      id: test-run
      run: |
        cd integration
        echo "Test Runner config"
        export TEST_RUNNER_SERVER_SPECIFICATION_FILE=${{ inputs.test-server }}
        resultsDir=/tmp/results$RANDOM
        echo "Running test suite ${{ inputs.test }} on ${{ inputs.test-server }}"
        ../gradlew :integration:runTest --args="${{ inputs.test }} $resultsDir" --scan
        testResult=$?
        echo "Test result is $testResult"
# TODO: decide whether we want to upload to the google bucket
#        echo "Upload test results to Google Bucket"
#        ../gradlew :integration:uploadResults --args="CompressDirectoryToTerraKernelK8S.json $resultsDir"
#        echo "Upload test results to BigQuery Test Runner Dataset"
#        ../gradlew :integration:uploadResults --args="SummariesToTerraKernelK8SBigQuery.json $resultsDir"
        exit $testResult
      shell: bash
