name: 'write-config'
description: 'Collect the vault information used for testing'
author: 'dd'
inputs:
  vault-token:
    description: 'Vault token'
    required: true
  target:
    description: 'Target environment: local, dev, alpha, staging or another personal namespace'
    default: 'local'
    required: true
outputs:
  target-txt:
    value: ${{ steps.files-to-outputs.outputs.target-txt }}
runs:
  using: "composite"
  steps:
    - name: Write configuration
      run: ./scripts/write-config.sh ${{ inputs.target }} ${{ inputs.vault-token }}
      shell: bash
    - name: Files to outputs
      id: files-to-outputs
      run: |
        echo "::set-output name=target-txt::$(<./config/target.txt)"
      shell: bash
