name: Build and Test

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - '*.md'
      - '.github/**'
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # rather than specifying the health check here, we do it manually later so we don't have to wait

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}

#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew

        # Build while waiting for the database to start since we use it for tests
      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Make sure Postgres is ready and init
        env:
          PGPASSWORD: postgres
        run: |
          pg_isready -t 10
          psql -h localhost -U postgres -f ./common/postgres-init.sql

      - name: Test with Gradle
        run: ./gradlew test
