# This workflow runs ECM's nightly tests, which currently only includes performance tests

name: Nightly Tests

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 7 * * *' # run at 7 AM UTC, 2 AM ET.
  pull_request:
    branches: [ '**' ]

jobs:
  performance-tests:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ github.ref }}-${{ github.sha }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ github.ref }}

      # Github workflows shouldn't have access to vault, so we read from GitHub secrets instead.
      - name: Render GitHub Secrets
        env:
          DEV_FIRECLOUD_ACCOUNT_B64: ${{ secrets.DEV_FIRECLOUD_ACCOUNT_B64 }}
          TESTRUNNER_PERF_SA: ${{ secrets.PERF_TESTRUNNER_ACCOUNT_B64 }}
        run: |
          echo "$DEV_FIRECLOUD_ACCOUNT_B64" | base64 -d >"./integration/src/main/resources/rendered/user-delegated-sa.json"
          echo "$TESTRUNNER_PERF_SA" | base64 -d >"./integration/src/main/resources/rendered/testrunner-sa.json"
      - name: Run the perf test suite
        run: ./gradlew --build-cache :integration:runTest --args="suites/FullPerf.json /tmp/foo"

  # notify-slack:
  #   needs: [ performance-tests ]
  #   runs-on: ubuntu-latest

  #   if: failure()

  #   steps:
  #     - name: Notify slack on failure
  #       uses: 8398a7/action-slack@v3
  #       env:
  #         SLACK_WEBHOOK_URL: ${{ secrets.POLICY_INT_WEBHOOK_URL }}
  #       with:
  #         status: failure
  #         author_name: Test Runner
  #         fields: workflow,message
  #         text: 'Nightly perf tests failed :sadpanda: (<https://github.com/DataBiosphere/terra-external-credentials-manager/actions/runs/$GITHUB_RUN_ID|link>)'
