# Action for running client integration tests against PRs. This test uses local
# server changes but runs a published version of the client, so it will not pick
# up local client changes.

name: PR Integration Tests
on:
  push:
    branches: [ dev ]
    paths-ignore:
      - 'README.md'
      - '.github/**'
      - 'service/local-dev/**'
  pull_request:
    branches: [ '**' ]
    # This is a required check for all PRs, so don't add a paths-ignore here.
    # We want this to always run so that the check passes.
jobs:
  pr-integration-job:

    runs-on: ubuntu-latest

    services:
      # TODO: see if there is a simpler way to do this pg check & init
      postgres:
        image: postgres:13.1
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Initialize Postgres DB for local server test run
        env:
          PGPASSWORD: postgres
        run: psql -h localhost -U postgres -f ./common/postgres-init.sql

      # TODO: check that this is what we do elsewhere
      - name: Set up AdoptOpenJDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # TODO: see if there is a better way to do this (maybe Monster has one?)
      - name: Get Vault token
        id: vault-token-step
        env:
          VAULT_ADDR: https://clotho.broadinstitute.org:8200
        run: |
          VAULT_TOKEN=$(docker run --rm --cap-add IPC_LOCK \
            -e "VAULT_ADDR=${VAULT_ADDR}" \
            vault:1.1.0 \
            vault write -field token \
              auth/approle/login role_id=${{ secrets.VAULT_APPROLE_ROLE_ID }} \
              secret_id=${{ secrets.VAULT_APPROLE_SECRET_ID }})
          echo ::set-output name=vault-token::$VAULT_TOKEN
          echo ::add-mask::$VAULT_TOKEN

      - name: Read configs from vault
        run: ./render_config.sh dev ${{ inputs.vault-token }}

      - name: Launch local server
        uses: ./.github/actions/start-local-server

      - name: Run the integration test suite
        id: integration-test
        run: |
          cd integration
          resultsDir=/tmp/results$RANDOM
          echo "Running the FullIntegration test suite"
          ../gradlew :integration:runTest --args="suites/FullIntegration.json $resultsDir" --scan
          testResult=$?
          echo "Test result is $testResult"
          exit $testResult
        shell: bash
