name: Bump, Tag, Publish, and Deploy
# The purpose of the workflow is to:
#  1. Bump the version number and tag the release
#  2. Build and publish the client to Artifactory
#  3. Build docker image and publish to GCR
#  4. Trigger deployment to the dev environment
#
# When run on merge to dev, it tags and bumps the patch version by default. You can
# bump other parts of the version by putting #major, #minor, or #patch in your commit
# message.
#
# When run on a hotfix branch, it tags and generates the hotfix version
#
# When run manually, you can specify the part of the semantic version to bump
#
# The workflow relies on github secrets:
# - ARTIFACTORY_PASSWORD - password for publishing the client to artifactory
# - ARTIFACTORY_USERNAME - username for publishing the client to artifactory
# - GCR_PUBLISH_EMAIL - email for publishing the docker to GCR
# - GCR_PUBLISH_KEY   - key for publishing the docker to GCR
# - BROADBOT_TOKEN - the broadbot token, so we can avoid two reviewer rule on GHA operations
on:
  push:
    branches:
    - dev
    paths-ignore:
    - '*.md'
    - '.github/**'
    tags-ignore:
      - * # tags will be generated by this action, so we don't need to run again on them

env:
  SERVICE_NAME: ${{ github.event.repository.name }}
  GOOGLE_PROJECT: terra-kernel-k8s
  GKE_CLUSTER: terra-kernel-k8s

jobs:
  tag-publish-job:
    runs-on: ubuntu-latest
    steps:
    - name: Set part of semantic version to bump
      id: semver
      run: |
        SEMVER_PART=""
        if ${{github.event_name == 'push' }}; then
          SEMVER_PART="patch"
        fi
        echo ::set-output name=semver-part::$SEMVER_PART
    - name: Checkout current code
      uses: actions/checkout@v2
    - name: Bump the tag to a new version
      uses: databiosphere/github-actions/actions/bumper@bumper-0.0.3
      id: tag
      env:
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ secrets.BROADBOT_TOKEN }}
        HOTFIX_BRANCHES: hotfix.*
        OVERRIDE_BUMP: ${{ steps.controls.outputs.semver-part }}
        RELEASE_BRANCHES: dev
        VERSION_FILE_PATH: build.gradle
        VERSION_LINE_MATCH: "^\\sversion\\s*=\\s*'.*'"
        VERSION_SUFFIX: SNAPSHOT
    - name: Checkout new tag # so it can be parsed to generate version info on build
      uses: actions/checkout@v2
      with:
        ref: ${{ steps.tag.outputs.tag }}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
        restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
#    - name: "Publish to Artifactory"
#      run: ./gradlew :client:artifactoryPublish
#      env:
#        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
#        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
#        ARTIFACTORY_REPO_KEY: "libs-snapshot-local"
    - name: Auth to GCR
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ secrets.GCR_PUBLISH_EMAIL }}
        service_account_key: ${{ secrets.GCR_PUBLISH_KEY }}
    - name: Explicitly auth Docker for GCR
      run: gcloud auth configure-docker --quiet
    - name: Construct docker image name and tag
      id: image-name
      run: echo ::set-output name=name::gcr.io/${GOOGLE_PROJECT}/${SERVICE_NAME}:${{ steps.tag.outputs.tag }}
    - name: Build image locally with jib
      run: "./gradlew :service:jibDockerBuild --image=${{ steps.image-name.outputs.name }} -Djib.console=plain"
    - name: Run Trivy vulnerability scanner
      # Link to the github location of the action https://github.com/broadinstitute/dsp-appsec-trivy-action
      uses: broadinstitute/dsp-appsec-trivy-action@v1
      with:
        image: ${{ steps.image-name.outputs.name }}
    - name: Push GCR image
      run: "docker push ${{ steps.image-name.outputs.name }}"
    - name: Deploy to Terra Dev environment
      if: github.event_name == 'push'
      uses: broadinstitute/repository-dispatch@master
      with:
        token: ${{ secrets.BROADBOT_TOKEN }}
        repository: broadinstitute/terra-helmfile
        event-type: update-service
        client-payload: '{"service": "externalcreds", "version": "${{ steps.tag.outputs.tag }}", "dev_only": false}'
